### ISSUE TITLE
Rotate screen

### ISSUE THREAD

**Issue by leonols** [makerbase-mks/MKS-SKIPR#1]
I'm put MKS SKIPR with PI-TS35 in to Sapphire PRO printer but screen on PI-TS35 is upside down. It is possible to rotate the screen 180 °.

**Comment by leonols** [comment]
Ok, i’m find the solution.

**Comment by adicrescenzo** [comment]
The solution is reported here: https://github.com/makerbase-mks/MKS-PI/blob/main/README.md#how-to-rotate-180-for-the-ts35-display
