### ISSUE TITLE
how to use HDMI?

### ISSUE THREAD

**Issue by gabber130779** [makerbase-mks/MKS-SKIPR#10]
hello.

how can i use the HDMI Port? When i connect a HDMI display, my display say "NO SIGNAL"

**Comment by rafalkor5** [comment]
Hello, Do you have a finished image from the factory on emc memory ? 

On this finished system, all I had to do was plug in the cable run the printer and right away the image was there :)

**Comment by gabber130779** [comment]
Did you use a normal computer monitor? I want to use a 5" display.

**Comment by rafalkor5** [comment]
I use 7 inch screen from aliexprerss.
