### ISSUE TITLE
3D Model

### ISSUE THREAD

**Issue by derTimm0** [makerbase-mks/MKS-SKIPR#3]
hi, my SKIPR is on the way. Its possible to get a 3D Model of the board for creating a case for it? Its to new for find some stuff on thinki eg.

**Comment by mks-viva** [comment]
You can refer to here: https://github.com/makerbase-mks/MKS-SKIPR/blob/main/hardware/MKS%20SKIPR%20V1.0_002/MKS%20SKIPR%20V1.0_002%203D.zip

**Comment by derTimm0** [comment]
thx
