### ISSUE TITLE
Cant reach the board over WiFi

### ISSUE THREAD

**Issue by PinGuiNPL** [makerbase-mks/MKS-SKIPR#33]
Hi, 
I've been trying to solve a problem since yesterday. 
The connection works perfectly with a LAN cable, but the attempt to connect to the WIFI fails. 
Only if I enter the command "sudo dhclient -v" via (LAN)SSH does the board find the IP that I have already set in the router for the WiFi connection. 
Unfortunately, even then I can't connect properly, when I enter the IP, the Mainsail interface shows the window "Connecting to 192.***.*.**", alternating with "initializing" but unfortunately it never works beyond this window.
I can then also connect via WiFi through SSH, but unfortunately with errors, as if I had no access to the storage space. Can't make updates aso.

What ive tried:
- configured "wpa_supplicant-wlan0.conf"
- added "timeout 5" to the "dhcpcd.conf"
- edited "/etc/network/interfaces"
- edited "/etc/netplan/50-cloud-init.yaml"
- edited "/etc/network/interfaces.d/wlan0"
- installed realtek drivers
- tried system on EMMC and on SDCard system

I don't know what to try next. I don't want to leave the printer connected to the LAN cable because I would have to leave a 10m long cable halfway through the room.
I'm using the "comfast cf-wu810n" WiFi Stick that comes with the board.

EDIT for more informations:

Before i "sudo dhclient -v" i get this when i try "ip a":
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ##:#M:#A:#C:##:## brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.3/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether ##:#M:#A:#C:##:## brd ff:ff:ff:ff:ff:ff

NO IP for WiFi... after "sudo dhclient -v"

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ##:#M:#A:#C:##:## brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.3/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ##:#M:#A:#C:##:## brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.36/24 brd 192.168.1.255 scope global dynamic wlan0
       valid_lft 86373sec preferred_lft 86373sec

there is the IP... for LAN 192.168.1.3 and for WiFi 192.168.1.36.... like i set it on my router...

**Comment by mozg4D** [comment]
will probably not help, but you must set not empty password for wifi in your router settings (192.168.1.1) to use "wpa-psk"

**Comment by PinGuiNPL** [comment]
> will probably not help, but you must set not empty password for wifi in your router settings (192.168.1.1) to use "wpa-psk"

I've always had it set that way.

BUT i found a solution...
Armbian_23.02.0-trunk_Mkspi_bullseye_current_5.15.91.img

It's a community image which is much more up-to-date than that of MKS. This, with a small modification to make my 7 inch display work, eliminated all other problems I had with the official image.

Here the github link for this project:
https://github.com/redrathnure/armbian-mkspi
