### ISSUE TITLE
HDMI doesn't work

### ISSUE THREAD

**Issue by yammaster** [makerbase-mks/MKS-SKIPR#37]
What's necessary that HDMI works? If I connect the IPS50 display via HDMI interface, nothing will shown. Is there anything to configure?

**Comment by PinGuiNPL** [comment]
SSH into the board and type
```
sudo nano /etc/X11/xorg.conf.d/40-monitor.conf
```
Put this there:
```
Section "Monitor" 
Identifier "HDMI-1"
Option "PreferredMode" "720x480"
EndSection
```
save.... then
```
sudo service KlipperScreen restart
```
Try different resolutions, till it works :)

**Comment by yammaster** [comment]
... should I configure printer.cfg that it shows on HDMI?

**Comment by EmJay276** [comment]
@yammaster did you manage to get it work?

**Comment by yammaster** [comment]
Hello, not yet the hints doesn't solve the problem. But I've seen, there is a new image available where the HDMI is special mentioned.RegardsRene--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 30.03.23, 23:00 schrieb "Michael Jäger" ***@***.***>:

   
  @yammaster did you manage to get it work?

**Comment by EmJay276** [comment]
If I'll get it to work, I will let you know.

**Comment by EmJay276** [comment]
@yammaster I figured it out! I had to flash the new image 
"Armbian-makerbase-k5.16.20-EN-20230301.img" onto the eMMC to get the IPS50 working!

**Comment by yammaster** [comment]
Yes, I got the IPS working.

**Comment by EmJay276** [comment]
> Yes, I got the IPS working.

How?

**Comment by yammaster** [comment]
I followed this guide, without the x-server calibration part and it works:

https://github.com/NexGen-3D-Printing/MKS-SKIPR-SETUP/blob/main/IPS50%20Fix
