### ISSUE TITLE
Z2, Z3 and Z4 - convert do E2, E3 and empty?

### ISSUE THREAD

**Issue by manuelchaves** [makerbase-mks/MKS-SKIPR#51]
Hello friends, I ask:
- Is it possible to convert Z2 and Z3 to E2 and E3? If so, how do I do it in Klipper?
- if you don't use Z4, can I leave it without a driver or do I need to leave an ok driver without use?
Thanks

**Comment by coyothG** [comment]
E possivel sim amigo, só  copiar o da primeira extrusora e usar as pinagem dos eixos que for usar! Em questao de se nao uzar o eixo z4 é so descomentarcou apagar os dados do z4 e os dados dos drives referente ao eixo!

**Comment by manuelchaves** [comment]
Tks, to twin Z axis I clone Z1 to Z2, change PIN only? tks
