### ISSUE TITLE
How to get Printer.cfg example for Cartesian Printer?

### ISSUE THREAD

**Issue by gabber130779** [makerbase-mks/MKS-SKIPR#8]
Hello, 

is it possible to get a example printer.cfg for a Cartesian Printer. ther is only one for Voron 2.4

**Comment by Shamoon78** [comment]
MKS made this nice board but there support to help peoples out fixing problems is absent .very sad.

**Comment by MKS-hosiey** [comment]
> 



> MKS made this nice board but there support to help peoples out fixing problems is absent .very sad, if there support is helpfull, I am going to order in bulk to Australia. but no way.

If you encounter problems, you can contact the technicians online on facebook

**Comment by Shamoon78** [comment]
facebook link?

**Comment by Townie-au** [comment]
You can just edit the printer.cfg file.
I've got everything working on Ender 3 except stock LCD screen. 
I can't work out the pins
